In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/job_data.csv')

In [14]:
df.head()

,title,location,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,text,text_length
0,Marketing Intern,"US, NY, New York","We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,,0,1,0,Other,Internship,Unknown,Unknown,Marketing,0,"Marketing Intern US, NY, New York We're Food52...",2708
1,Customer Service - Cloud Video Production,"NZ, , Auckland","90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,Unknown,Marketing and Advertising,Customer Service,0,"Customer Service - Cloud Video Production NZ, ...",6217
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,,0,1,0,Unknown,Unknown,Unknown,Unknown,Unknown,0,"Commissioning Machinery Assistant (CMA) US, IA...",2659
3,Account Executive - Washington DC,"US, DC, Washington",Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,"Account Executive - Washington DC US, DC, Wash...",5550
4,Bill Review Manager,"US, FL, Fort Worth",SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,"Bill Review Manager US, FL, Fort Worth SpotSou...",4057

In [15]:
df.isnull().sum().sort_values(ascending=False)

title                  0
location               0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
text                   0
text_length            0
dtype: int64

In [8]:
text_columns = [
    "title",
    "location",
    "company_profile",
    "description",
    "requirements",
    "benefits"
]

df[text_columns] = df[text_columns].fillna("")

In [9]:
categorical_cols = [
    "employment_type",
    "required_experience",
    "required_education",
    "industry",
    "function"
]

df[categorical_cols] = df[categorical_cols].fillna("Unknown")

In [10]:
df.isnull().sum()

title                  0
location               0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
text                   0
text_length            0
dtype: int64

In [12]:
df['text'].isnull().sum()

np.int64(0)

In [28]:
import re
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [20]:
## lowercasing
df['text'] = df['text'].str.lower()

## removing html tags
df["text"] = df["text"].apply(lambda x: re.sub(r"<.*?>"," ",x))

## remove special numbers
df["text"] = df["text"].apply(lambda x: re.sub(r"[^a-zA-Z\s]"," ",x))

In [26]:
df.loc[2,'text']

'commissioning machinery assistant  cma  us  ia  wever valor services provides workforce solutions that meet the needs of companies across the private sector  with a special focus on the oil  amp  gas industry \xa0valor services will be involved with you throughout every step of the hiring process and remain in contact with you all the way through the final step of signing of the employment contract with your new employer \xa0valor services was founded with the vision of employing the unique skills  experiences  and qualities of america s finest veterans to provide private sector companies with precise and concerted value added services   and america s finest veterans with an optimized career opportunity we are eager to get the word out to veterans that there are ample opportunities for employment in the private sector and that you are the ideal candidates to fill those positions \xa0valor services\xa0your success is our mission \xa0 \xa0 our client  located in houston  is actively seeking an experienced commissioning machinery assistant that possesses strong supervisory skills and has an attention to detail  a strong dedication to safety is a must  the ideal candidate will execute all activities while complying with quality requirements and health  environmental  and safety regulations  implement pre commissioning and commissioning procedures for rotary equipment execute all activities with subcontractor s assigned crew that pertains to the discipline ensure effective utilization of commissioning manpower and consumables ensure the execution of vendor specialists  field activities with the assigned resources from the sub contractor per vendor s representative plans carry out equipment inspections with client representatives and ensure proper certification is produced prepare forms for all pending tests and submit signed certificates for final hand over to the certification engineer for qa and qc coordinate in the field with vendor representatives keep records of all activities ensure that safety practices are strictly followed during the execution of activities report progress and constraints to the mechanical supervisor possible authorization by site manager to receive or issue a permit to work according to project permit to work procedures assist supervisor to expedite pending punch list items in accordance with the commissioning manager s priorities assist supervisor to coordinate and supervise construction support activities during pre commissioning and commissioning activities company overview our client is a premiere engineering  construction  and procurement company that executes large scale projects internationally       '

In [29]:
## tokenization

df['tokens'] = df['text'].apply(word_tokenize)

In [31]:
df.head(2)

,title,location,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,text,text_length,tokens
0,Marketing Intern,"US, NY, New York","We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,,0,1,0,Other,Internship,Unknown,Unknown,Marketing,0,marketing intern us ny new york we re food ...,2708,"[marketing, intern, us, ny, new, york, we, re,..."
1,Customer Service - Cloud Video Production,"NZ, , Auckland","90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,Unknown,Marketing and Advertising,Customer Service,0,customer service cloud video production nz ...,6217,"[customer, service, cloud, video, production, ..."

In [32]:
df[["text","tokens"]].head()

,text,tokens
0,marketing intern us ny new york we re food ...,"[marketing, intern, us, ny, new, york, we, re,..."
1,customer service cloud video production nz ...,"[customer, service, cloud, video, production, ..."
2,commissioning machinery assistant cma us ia...,"[commissioning, machinery, assistant, cma, us,..."
3,account executive washington dc us dc wash...,"[account, executive, washington, dc, us, dc, w..."
4,bill review manager us fl fort worth spotsou...,"[bill, review, manager, us, fl, fort, worth, s..."

In [45]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
df['token'] = df['tokens'].apply(
  lambda words: [w for w in words if w not in stop_words]
)

In [46]:
from nltk.stem import WordNetLemmatizer
Lematize = WordNetLemmatizer()
df["token"] = df["tokens"].apply(
    lambda words: [Lematize.lemmatize(w) for w in words]
)

In [47]:
df.head(2)

,title,location,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,...,industry,function,fraudulent,text,text_length,tokens,lemma_tokens,cleam_text,clean_text,token
0,Marketing Intern,"US, NY, New York","We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,,0,1,0,Other,...,Unknown,Marketing,0,marketing intern us ny new york we re food ...,2708,"[marketing, intern, u, ny, new, york, we, re, ...","[marketing, intern, us, ny, new, york, food, c...",marketing intern us ny new york food created g...,marketing intern us ny new york food created g...,"[marketing, intern, u, ny, new, york, we, re, ..."
1,Customer Service - Cloud Video Production,"NZ, , Auckland","90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,...,Marketing and Advertising,Customer Service,0,customer service cloud video production nz ...,6217,"[customer, service, cloud, video, production, ...","[customer, service, cloud, video, production, ...",customer service cloud video production nz auc...,customer service cloud video production nz auc...,"[customer, service, cloud, video, production, ..."

In [48]:
df.rename(columns={"token": "lemma_tokens"}, inplace=True)

In [43]:
df['clean_text'] = df['lemma_tokens'].apply(lambda x: " ".join(x))

In [49]:
df[["text","clean_text"]].head()

,text,clean_text
0,marketing intern us ny new york we re food ...,marketing intern us ny new york food created g...
1,customer service cloud video production nz ...,customer service cloud video production nz auc...
2,commissioning machinery assistant cma us ia...,commissioning machinery assistant cma us ia we...
3,account executive washington dc us dc wash...,account executive washington dc us dc washingt...
4,bill review manager us fl fort worth spotsou...,bill review manager us fl fort worth spotsourc...

In [52]:
df = df.drop(columns=["tokens","lemma_tokens" , "cleam_text"], errors="ignore")

In [54]:
df.columns

Index(['title', 'location', 'company_profile', 'description', 'requirements',
       'benefits', 'telecommuting', 'has_company_logo', 'has_questions',
       'employment_type', 'required_experience', 'required_education',
       'industry', 'function', 'fraudulent', 'text', 'text_length',
       'clean_text'],
      dtype='object')

In [56]:
### Apply some hueristic features by understanding the data
df["missing_company_profile"] = df["company_profile"].apply(lambda x: 1 if x=="" else 0)

df["missing_benefits"] = df["benefits"].apply(lambda x: 1 if x=="" else 0)


df["short_description"] = df["text_length"].apply(lambda x: 1 if x < 500 else 0)

In [57]:
df.head(2)

,title,location,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,...,required_education,industry,function,fraudulent,text,text_length,clean_text,missing_company_profile,missing_benefits,short_description
0,Marketing Intern,"US, NY, New York","We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,,0,1,0,Other,...,Unknown,Unknown,Marketing,0,marketing intern us ny new york we re food ...,2708,marketing intern us ny new york food created g...,0,1,0
1,Customer Service - Cloud Video Production,"NZ, , Auckland","90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,...,Unknown,Marketing and Advertising,Customer Service,0,customer service cloud video production nz ...,6217,customer service cloud video production nz auc...,0,0,0

In [59]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [60]:
df.to_csv("/content/drive/MyDrive/preprocessed_fake_job_data.csv", index=False)

In [58]:
df.columns

Index(['title', 'location', 'company_profile', 'description', 'requirements',
       'benefits', 'telecommuting', 'has_company_logo', 'has_questions',
       'employment_type', 'required_experience', 'required_education',
       'industry', 'function', 'fraudulent', 'text', 'text_length',
       'clean_text', 'missing_company_profile', 'missing_benefits',
       'short_description'],
      dtype='object')

In [61]:
model_df = df[[
    "clean_text",
    "text_length",
    "telecommuting",
    "has_company_logo",
    "has_questions",
    "missing_company_profile",
    "missing_benefits",
    "short_description",
    "fraudulent"
]]

In [62]:
model_df.head()

,clean_text,text_length,telecommuting,has_company_logo,has_questions,missing_company_profile,missing_benefits,short_description,fraudulent
0,marketing intern us ny new york food created g...,2708,0,1,0,0,1,0,0
1,customer service cloud video production nz auc...,6217,0,1,0,0,0,0,0
2,commissioning machinery assistant cma us ia we...,2659,0,1,0,0,1,0,0
3,account executive washington dc us dc washingt...,5550,0,1,0,0,0,0,0
4,bill review manager us fl fort worth spotsourc...,4057,0,1,1,0,0,0,0

In [69]:
df = pd.read_csv('/content/drive/MyDrive/model_fake_data.csv')

In [68]:
df.head(3)

,title,location,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,...,required_education,industry,function,fraudulent,text,text_length,clean_text,missing_company_profile,missing_benefits,short_description
0,Marketing Intern,"US, NY, New York","We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,...,Unknown,Unknown,Marketing,0,marketing intern us ny new york we re food ...,2708,marketing intern us ny new york food created g...,0,1,0
1,Customer Service - Cloud Video Production,"NZ, , Auckland","90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,...,Unknown,Marketing and Advertising,Customer Service,0,customer service cloud video production nz ...,6217,customer service cloud video production nz auc...,0,0,0
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,Unknown,...,Unknown,Unknown,Unknown,0,commissioning machinery assistant cma us ia...,2659,commissioning machinery assistant cma us ia we...,0,1,0

In [70]:
df.head(3)

,clean_text,text_length,telecommuting,has_company_logo,has_questions,missing_company_profile,missing_benefits,short_description,fraudulent
0,marketing intern us ny new york food created g...,2708,0,1,0,0,1,0,0
1,customer service cloud video production nz auc...,6217,0,1,0,0,0,0,0
2,commissioning machinery assistant cma us ia we...,2659,0,1,0,0,1,0,0

## Text Preprocessing

Text preprocessing is performed to clean and normalize the job posting text so that it can be effectively used by machine learning models.

The following steps were applied:

* **Lowercasing:** Converted all text to lowercase to maintain consistency.
* **Removing special characters:** Removed punctuation and unnecessary symbols.
* **Tokenization:** Split text into individual words (tokens).
* **Stopwords removal:** Removed common words such as *the, is, and* that do not add meaningful information.
* **Lemmatization:** Converted words to their base form (e.g., *running → run*).

Finally, the processed tokens were combined back into a cleaned text column called **`clean_text`**, which will be used for feature extraction in the modeling phase.